name: A workflow for my Hello World file
on: push

jobs:
  pythonScript:
    runs-on: ubuntu-latest
    name: Hello world action
    steps:
      - name: Python task
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      run: python python_script.py

          